export const getCards = () => {
    const data = [
        {type: "Misfortune", name: "La desgracia esta contigo", wtdoes: "Pierdes 5 Dólares."},
        {type: "Misfortune", name: "Te han robado", wtdoes: "Pierdes 4 Dólares."},
        {type: "Misfortune", name: "Tropezaste con algo", wtdoes: "Pierdes 3 Dólares."},
        {type: "Misfortune", name: "Te estafaron", wtdoes: "Pierdes 2 Dólares."},
        {type: "Misfortune", name: "Pudo ser peor", wtdoes: "Pierdes 1 Dólar."},
        {type: "Fortune", name: "Adicto al dinero", wtdoes: "Ganas 5 Dólares."},
        {type: "Fortune", name: "La suerte te sonríe", wtdoes: "Ganas 4 Dólares."},
        {type: "Fortune", name: "Se huele la suerte", wtdoes: "Ganas 3 Dólares."},
        {type: "Fortune", name: "Encontraste algo", wtdoes: "Ganas 2 Dólares."},
        {type: "Fortune", name: "Algo es algo", wtdoes: "Ganas 1 Dólar."},
        {type: "Random", name: "Segundas oportunidades", wtdoes: "Vuelve a tirar el dado otra vez."},
        {type: "Random", name: "Dinero y suerte, tus mejores amigos", wtdoes: "Avanza 3 casillas y gana 3 dólares."},
        {type: "Random", name: "Buen tiro", wtdoes: "Avanza 1 casilla."},
        {type: "Random", name: "A la carga", wtdoes: "Avanza 2 casillas."},
        {type: "Random", name: "Correcaminos", wtdoes: "Avanza 3 casillas."},
        {type: "Random", name: "Tren bala", wtdoes: "Avanza 4 casillas."},
        {type: "Random", name: "Golpe", wtdoes: "Pierdes 1 turno."},
        {type: "Random", name: "Mundo inverso", wtdoes: "Tira el dado y retrocedes el número de casillas que te salga."},
        {type: "Random", name: "Suelo inestable", wtdoes: "Retrocede 1 casilla."},
        {type: "Random", name: "Corredor del tiempo", wtdoes: "Retrocede 2 casillas."},
        {type: "Random", name: "Atrás ¿mejor?", wtdoes: "Retrocede 3 casillas."},
        {type: "Random", name: "Retroceder, un estilo de vida", wtdoes: "Retrocede 4 casillas."},
        {type: "Random", name: "Donde mas duele", wtdoes: "Retrocede 5 casillas."},
        {type: "Challenge", name: "Cara o Sello", wtdoes: "Si aciertas, avanza 2 casillas. Si fallas, retrocede 1 casilla."},
        {type: "Challenge", name: "Adivina el Objeto", wtdoes: "Si aciertas, avanza 3 casillas y ganas 3 dólares. Si fallas, pierdes 1 turno."},
        {type: "Challenge", name: "Pulso", wtdoes: "Si ganas, vuelves a tirar el dado. Si pierdes, retrocedes 2 casillas."},
        {type: "Challenge", name: "Escritura al Revés", wtdoes: "Si ganas, avanza 1 casilla. Si pierdes, retrocede 1 casilla."},
        {type: "Challenge", name: "Reto de Dibujo", wtdoes: "Si ganas, avanza 2 casillas. Si pierdes, retrocede 1 casilla."},
        {type: "Challenge", name: "Puntería", wtdoes: "Si ganas, avanza 3 casillas y ganas 3 dólares. Si pierdes, retrocedes 2 casillas."},
        {type: "Challenge", name: "Tres en Raya", wtdoes: "Si ganas, avanza 1 casilla. Si pierdes, retrocede 1 casilla."},
        {type: "Challenge", name: "Reto del Equilibrio", wtdoes: "Si ganas, vuelves a tirar el dado. Si pierdes, retrocedes 1 casilla."},
        {type: "Challenge", name: "Competencia de Mímica", wtdoes: "Si ganas, avanza 2 casillas. Si pierdes, pierdes 1 turno."},
        {type: "Challenge", name: "Reto de Palabras Encadenadas", wtdoes: "Si ganas, avanza 1 casilla. Si pierdes, retrocede 1 casilla."},
        {type: "Challenge", name: "Dibuja lo que Sientes", wtdoes: "Si ganas, avanza 2 casillas. Si pierdes, retrocedes 1 casilla."},
        {type: "Challenge", name: "Cálculo Mental", wtdoes: "Si ganas, avanza 3 casillas y ganas 3 dólares. Si pierdes, retrocedes 1 casilla."},
        {type: "Challenge", name: "Piedra, Papel o Tijeras", wtdoes: "Si ganas, avanza 2 casillas. Si pierdes, retrocedes 2 casillas."},
        {type: "Challenge", name: "Encuentra Rápido", wtdoes: "Si ganas, vuelves a tirar el dado. Si pierdes, retrocedes 1 casilla."},

    ];
    
    return Promise.resolve(data);
      
};
