export const getCards = () => {
    const data = [
        {type: "Miss Fortune", name: "Pierdes 5 Dólares", wtdoes: "Pierdes 5 Dólares."},
        {type: "Miss Fortune", name: "Pierdes 4 Dólares", wtdoes: "Pierdes 4 Dólares."},
        {type: "Miss Fortune", name: "Pierdes 3 Dólares", wtdoes: "Pierdes 3 Dólares."},
        {type: "Miss Fortune", name: "Pierdes 2 Dólares", wtdoes: "Pierdes 2 Dólares."},
        {type: "Miss Fortune", name: "Pierdes 1 Dólar", wtdoes: "Pierdes 1 Dólar."},
        {type: "Fortune", name: "Ganas 5 Dólares", wtdoes: "Ganas 5 Dólares."},
        {type: "Fortune", name: "Ganas 4 Dólares", wtdoes: "Ganas 4 Dólares."},
        {type: "Fortune", name: "Ganas 3 Dólares", wtdoes: "Ganas 3 Dólares."},
        {type: "Fortune", name: "Ganas 2 Dólares", wtdoes: "Ganas 2 Dólares."},
        {type: "Fortune", name: "Ganas 1 Dólar", wtdoes: "Ganas 1 Dólar."},
        {type: "Random", name: "Vuelve a tirar el dado", wtdoes: "Vuelve a tirar el dado otra vez."},
        {type: "Random", name: "Avanza 3 casillas y gana 3 dólares", wtdoes: "Avanza 3 casillas y gana 3 dólares."},
        {type: "Random", name: "Avanza 1 casilla", wtdoes: "Avanza 1 casilla."},
        {type: "Random", name: "Avanza 2 casillas", wtdoes: "Avanza 2 casillas."},
        {type: "Random", name: "Avanza 3 casillas", wtdoes: "Avanza 3 casillas."},
        {type: "Random", name: "Avanza 4 casillas", wtdoes: "Avanza 4 casillas."},
        {type: "Random", name: "Pierdes 1 turno", wtdoes: "Pierdes 1 turno."},
        {type: "Random", name: "Retrocede según el dado", wtdoes: "Tira el dado y retrocedes el número de casillas que te salga."},
        {type: "Random", name: "Retrocede 1 casilla", wtdoes: "Retrocede 1 casilla."},
        {type: "Random", name: "Retrocede 2 casillas", wtdoes: "Retrocede 2 casillas."},
        {type: "Random", name: "Retrocede 3 casillas", wtdoes: "Retrocede 3 casillas."},
        {type: "Random", name: "Retrocede 4 casillas", wtdoes: "Retrocede 4 casillas."},
        {type: "Random", name: "Retrocede 5 casillas", wtdoes: "Retrocede 5 casillas."},
        {type: "Challenge", name: "Cara o Sello", wtdoes: "Si aciertas, avanza 2 casillas. Si fallas, retrocede 1 casilla."},
        {type: "Challenge", name: "Adivina el Objeto", wtdoes: "Si aciertas, avanza 3 casillas y ganas 3 dólares. Si fallas, pierdes 1 turno."},
        {type: "Challenge", name: "Pulso", wtdoes: "Si ganas, vuelves a tirar el dado. Si pierdes, retrocedes 2 casillas."},
        {type: "Challenge", name: "Escritura al Revés", wtdoes: "Si ganas, avanza 1 casilla. Si pierdes, retrocede 1 casilla."},
        {type: "Challenge", name: "Reto de Dibujo", wtdoes: "Si ganas, avanza 2 casillas. Si pierdes, retrocede 1 casilla."},
        {type: "Challenge", name: "Puntería", wtdoes: "Si ganas, avanza 3 casillas y ganas 3 dólares. Si pierdes, retrocedes 2 casillas."},
        {type: "Challenge", name: "Tres en Raya", wtdoes: "Si ganas, avanza 1 casilla. Si pierdes, retrocede 1 casilla."},
        {type: "Challenge", name: "Reto del Equilibrio", wtdoes: "Si ganas, vuelves a tirar el dado. Si pierdes, retrocedes 1 casilla."},
        {type: "Challenge", name: "Competencia de Mímica", wtdoes: "Si ganas, avanza 2 casillas. Si pierdes, pierdes 1 turno."},
        {type: "Challenge", name: "Reto de Palabras Encadenadas", wtdoes: "Si ganas, avanza 1 casilla. Si pierdes, retrocede 1 casilla."},
        {type: "Challenge", name: "Dibuja lo que Sientes", wtdoes: "Si ganas, avanza 2 casillas. Si pierdes, retrocedes 1 casilla."},
        {type: "Challenge", name: "Cálculo Mental", wtdoes: "Si ganas, avanza 3 casillas y ganas 3 dólares. Si pierdes, retrocedes 1 casilla."},
        {type: "Challenge", name: "Piedra, Papel o Tijeras", wtdoes: "Si ganas, avanza 2 casillas. Si pierdes, retrocedes 2 casillas."},
        {type: "Challenge", name: "Encuentra Rápido", wtdoes: "Si ganas, vuelves a tirar el dado. Si pierdes, retrocedes 1 casilla."},

    ];
    
    return Promise.resolve(data);
      
};
